Issues/1
ns-knowledgebase/shiritori pull request #2
Opened 2024-09-24 05:56 UTC by minagishl

### Changes Made

Added Issue and Pull Request templates to the repository to standardize and streamline the process of submitting issues and pull requests.

### Issues Resolved

This solves the problem of inconsistent and unclear submissions by providing structured templates for both issues and pull requests.

See #1

2024-09-24 05:58 UTC, minagishl commented
@tukiminya  I wasn't sure who the appropriate person was, so I added you. I would appreciate your review.

2024-09-24 06:14 UTC, tukiminya commented
@minagishl 
まずは対応ありがとうございます。
お願いにはなりますが、コミットメッセージ、Issue/PRタイトル以外の
「本文」の部分については読みやすさや、他の委員でもすぐに理解できるように日本語で書いていただけると嬉しいです。

内容については追って確認しますので少々お待ちください～

2024-09-24 06:16 UTC, minagishl commented
@tukiminya 承知しました、以後日本語で書かせていただきます

2024-09-25 13:00 UTC, tukiminya commented
@minagishl 
「しりとり」という日本特有のゲームの都合上、英語でのREADME.mdの整備や、
Issue/PR テンプレートは不要かと思いましたが、いかがでしょうか？

私としては日本語を採用したほうが、日本語のゲームに慣れている人にとって一番親しみやすいかな？と思っています。

2024-09-25 22:36 UTC, minagishl commented
@tukiminya 
レビューありがとうございます

私としては、テンプレートをこのイシューで日本語に変更し、README.md については新しく別のイシューを立てて日本語化するのが良いのではないかと考えているのですが、どうでしょうか？

2024-09-27 06:33 UTC, tukiminya commented
@minagishl 
そうしましょう！

2024-09-27 06:37 UTC, tukiminya requested changes
日本語に書き直すようにお願いします！
完了したら、Re-reviewの提出をお願いします！

2024-09-27 06:56 UTC, minagishl commented
@tukiminya 修正しました、再度レビューよろしくお願い致します

2024-09-28 13:36 UTC, tukiminya requested changes
ひとまずこちらの対応をお願いします！

2024-09-28 13:36 UTC, tukiminya commented on .github/ISSUES_TEMPLATE/bug_report.md
> +バグを再現する手順
```suggestion
バグを再現する手順を段階的に、具体性を持って説明してください
```

2024-09-28 13:36 UTC, tukiminya commented on .github/ISSUES_TEMPLATE/bug_report.md
> +<!-- 以下の項目は必須ではありませんので、不要な場合は削除してください -->
そのままで問題ないかと思います！
```suggestion
```

2024-09-28 13:36 UTC, tukiminya commented on .github/ISSUES_TEMPLATE/feature_request.md
> +<!-- 以下の項目は必須ではありませんので、不要な場合は削除してください -->
そのままで問題ないかと思います！
```suggestion
```

2024-09-29 00:19 UTC, minagishl commented
@tukiminya 修正しました、ご確認よろしくお願いします

2024-09-29 10:33 UTC, tukiminya approved these changes
私は問題ないです！
@GakutoHirose どうでしょうか？

2024-09-30 08:11 UTC, GakutoHirose commented
LGTM

2024-09-30 08:11 UTC, GakutoHirose approved these changes
LGTM!!

2024-09-30 10:37 UTC, merged